Name:           perl-Date-Manip
Version:        6.30
Release: 	1%{?dist}
Summary:        A Perl module containing a wide variety of date manipulation routines
Summary(zh_CN.UTF-8): 包含广泛的日期操作例程的 Perl 模块。

Group:          Development/Libraries
Group(zh_CN.UTF-8): 	开发/库
License:        GPL or Artistic
URL:            http://search.cpan.org/dist/Date-Manip/
Source0:  http://www.cpan.org/authors/id/S/SB/SBECK/Date-Manip-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildArch:      noarch
BuildRequires:  perl >= 1:5.6.1
Requires:  perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

Provides:  perl-DateManip = %{version}-%{release}
Obsoletes: perl-DateManip

%description
This is a set of routines designed to make any common date/time
manipulation easy to do.  Operations such as comparing two times,
calculating a time a given amount of time from another, or parsing
international times are all easily done.

%description -l zh_CN.UTF-8
这是一个例程集合。它的目的是简易化常用的日期和时间操作。这些操作如：
比较两个时间、从一个时间中计算另一个时间、或者解析国际时间，它们都可
以被简单地完成。

%prep
%setup -q -n Date-Manip-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null ';'
chmod -R u+w $RPM_BUILD_ROOT/*

%check

%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc README
%{perl_vendorlib}/Date/
%{_mandir}/man3/*.3*


%changelog
* Tue Oct 10 2006 Liu Di <liudidi@gmail.com> - 5.44-1mgc
- rebuild for Magic

* Wed Jul 12 2006 Jesse Keating <jkeating@redhat.com> - sh: line 0: fg: no job control
- rebuild

* Fri Feb 03 2006 Jason Vas Dias <jvdias@redhat.com> - 5.44-1.2
- rebuild for new perl-5.8.8

* Fri Dec 16 2005 Jesse Keating <jkeating@redhat.com>
- rebuilt for new gcc

* Fri Sep  9 2005 Jose Pedro Oliveira <jpo at di.uminho.pt> - 5.44-1
- Update to 5.44.

* Mon Apr 25 2005 Jose Pedro Oliveira <jpo at di.uminho.pt> - 5.42a-4
- Bring up to date with current Fedora.Extras perl spec template. (#155913)

* Wed Sep 22 2004 Chip Turner <cturner@redhat.com> 5.42a-2
- rebuild

* Fri Feb 13 2004 Chip Turner <cturner@redhat.com> 5.42a-1
- update to 5.42a

* Tue Aug  6 2002 Chip Turner <cturner@redhat.com>
- automated release bump and build

* Wed Jan 09 2002 Tim Powers <timp@redhat.com>
- automated rebuild

* Fri Dec 7 2001 root <root@redhat.com>
- Spec file was autogenerated.
